# Generated by Django 5.0.6 on 2025-02-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/avatars"),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
