# Generated by Django 5.0.6 on 2025-02-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_photo_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="score_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="score_views",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
