# Generated by Django 5.0.6 on 2025-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_score_likes_alter_user_score_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="score_publications",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
