# Generated by Django 5.0.6 on 2025-02-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_score_publications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="score_dislikes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/users/avatars"
            ),
        ),
    ]
