# Generated by Django 5.0.6 on 2025-02-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="score_views",
        ),
        migrations.AlterField(
            model_name="user",
            name="score_dislikes",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="score_likes",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="score_publications",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
