# Generated by Django 5.0.6 on 2025-02-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_score_views_alter_user_score_dislikes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="score_dislikes",
        ),
    ]
