# Generated by Django 5.0.6 on 2025-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="articles/pic"),
        ),
    ]
