# Generated by Django 5.0.6 on 2025-02-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_id",
            new_name="autor_id",
        ),
    ]
