# Generated by Django 5.0.6 on 2025-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_comment_article_id_alter_comment_autor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(),
        ),
    ]
