# Generated by Django 5.0.6 on 2025-02-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(),
        ),
    ]
