# Generated by Django 5.1.7 on 2025-10-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='autor_id',
            new_name='author_id',
        ),
    ]
