# Generated by Django 5.0.6 on 2025-02-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_articles_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="dislikes",
        ),
    ]
