# Generated by Django 5.0.6 on 2025-02-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_article_likes_article_likes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
