# Generated by Django 5.0.6 on 2025-02-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_profile",
        ),
    ]
